module.exports = {
  name: 'antd admin spring-boot',
  version: '0.9.0',
  prefix: 'antdAdmin',
  footerText: 'Copyright © 2017. 进击的大黄 . All rights reserved',
  logo: '/logo.png',
  qrCode: '/QR_code.jpg',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: [],
  openPages: ['/login'],
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    weather: '/weather',
    dashboard: '/dashboard',
    common: {
      autoComplete: '/common/combox/autoComplete',
      select: '/common/combox/select',
      upload: '/common/file/upload',
      preview: '/common/file/preview',
      download: '/common/file/download',
    },
    sys: {
      accounts: '/sys/accounts',
      menus: '/sys/menus',
      permissions: '/sys/permissions',
      roles: '/sys/roles',
    },
  },
}
